# permissions for end users to view fateclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fatecluster-viewer-role
rules:
- apiGroups:
  - app.kubefate.net
  resources:
  - fateclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kubefate.net
  resources:
  - fateclusters/status
  verbs:
  - get
