# permissions for end users to edit kubefates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefate-editor-role
rules:
- apiGroups:
  - app.kubefate.net
  resources:
  - kubefates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kubefate.net
  resources:
  - kubefates/status
  verbs:
  - get
