apiVersion: app.kubefate.net/v1beta1
kind: FateCluster
metadata:
  name: fatecluster-sample
  namespace: fate-9999
spec:
  kubefate:
    name: kubefate-sample
    namespace:  kube-fate
  clusterSpec:
    name: fate-9999
    namespace: fate-9999
    chartName: fate
    chartVersion: v1.4.0-a
    partyId: 9999
    registry: ""
    pullPolicy: ""
    persistence: false
    istio:
      enabled: false
    modules:
      - rollsite
      - clustermanager
      - nodemanager
      - mysql
      - python
      - client

    rollsite:
      type: NodePort
      nodePort: 30009
      exchange:
        ip: 192.168.1.1
        port: 30000
      partyList:
        - partyId: 10000
          partyIp: 192.168.10.1
          partyPort: 30010
      nodeSelector: {}

    nodemanager:
      count: 3
      sessionProcessorsPerNode: 4
      list:
        - name: nodemanager
          nodeSelector: {}
          sessionProcessorsPerNode: 2
          subPath: "nodemanager"
          existingClaim: ""
          storageClass: "nodemanager"
          accessMode: ReadWriteOnce
          size: 1Gi

    python:
      fateflowType: NodePort
      fateflowNodePort: 30109
      nodeSelector: {}

    mysql:
      nodeSelector: {}
      ip: mysql
      port: 3306
      database: eggroll_meta
      user: fate
      password: fate_dev
      subPath: ""
      existingClaim: ""
      storageClass: "mysql"
      accessMode: ReadWriteOnce
      size: 1Gi

    # externalMysqlIp: mysql
    # externalMysqlPort: 3306
    # externalMysqlDatabase: eggroll_meta
    # externalMysqlUser: fate
    # externalMysqlPassword: fate_dev

    servingIp: 192.168.9.1
    servingPort: 30209
