apiVersion: app.kubefate.net/v1beta1
kind: Kubefate
metadata:
  name: kubefate-sample
  namespace: kube-fate
spec:
  # kubefate image tag
  image: federatedai/kubefate:v1.3.0
  # ingress host
  ingressDomain: kubefate.net
  # serviceAccountName
  serviceAccountName: kubefate-admin
  # kubefate config
  volumeSource:
    hostPath:
      path: /home/kubefate/mysql/db
      type: DirectoryOrCreate
  config:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: mariadbUsername
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: mariadbPassword
    - name: FATECLOUD_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: mariadbUsername
    - name: FATECLOUD_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: mariadbPassword
    - name: FATECLOUD_REPO_NAME
      value: "kubefate"
    - name: FATECLOUD_REPO_URL
      value: "https://federatedai.github.io/KubeFATE"
    - name: FATECLOUD_USER_USERNAME
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: kubefateUsername
    - name: FATECLOUD_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubefate-secret
          key: kubefatePassword
    - name: FATECLOUD_LOG_LEVEL
      value: "debug"
    - name: FATECLOUD_LOG_NOCOLOR
      value: "true"
